title: Carlos Keglevich # your name (or website title) here
logo: "/images/IMG_2811.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Analyst with a bachelor’s degree  
  in Business Administration.
  <br><br>
  Proficient in investiganting Data. Skilled in tools as Tableau, MS Power BI 
  Python and SQL Expert. I am interested in Data Engineering and software development
  <br>
  <a href="https://www.linkedin.com/in/carloskeglevich/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://github.com/Keglev/">View GitHub Repo</a> 
  <br>
theme: jekyll-theme-minimal
google_analytics: G-NSTWR76ZKB # your Google Analytics tracking ID here
