title: Carlos Keglevich # your name (or website title) here
logo: "/images/IMG_2811.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Recent Graduated in Data Analysis with a bachelor’s degree.  
  <br><br>
  in Business Administration.
  Skilled in utilizing tools such as Tableau, MS Power BI
   
  <br><br>
  <a href="https://www.linkedin.com/in/carloskeglevich">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
